# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('WAITING_PAYMENT', 'Attente de paiement'), ('RESERVED', 'Réservé'), ('CANCELLED_BY_USER', 'Annulé (Client)'), ('CANCELLED_BY_ADMIN', 'Annulé (Admin)'), ('CANCELLED_BY_UNPAYMENT', 'Annulé (Pas de paiement)')], max_length=255)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='meal.Day', verbose_name='Jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
