# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.CharField(default='8,50', max_length=255),
            preserve_default=False,
        ),
    ]
