# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_auto_20161017_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='price',
            field=models.IntegerField(verbose_name='Prix en CENTIMES'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(verbose_name='Prix en CENTIMES'),
        ),
    ]
