# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paypal_status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
