# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_transaction_paypal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouvelle')], default='NEW', max_length=255),
        ),
    ]
