# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Prix en CENTIMES'),
            preserve_default=False,
        ),
    ]
