# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0010_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='logs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
