# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0007_auto_20160219_1135'),
        ('meal', '0011_transaction_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ipns',
            field=models.ManyToManyField(related_name='transactions', to='ipn.PayPalIPN', verbose_name='IPNs'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouvelle'), ('ERROR', 'Erreur'), ('PENDING', 'En attente')], default='NEW', max_length=255),
        ),
    ]
