# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0016_auto_20161102_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
