# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0017_transaction_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='special',
            field=models.BooleanField(default=False, verbose_name='Est un jour spécial'),
        ),
    ]
